# vim: ft=dosini
#
# aerc Arrowlake styleset
# set styleset-name=arrowlake-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#312e55
border.bg=#0D0C25

title.fg=#070614
title.bg=#3F3BF5
title.bold=true

header.fg=#E50050
#header.bg=#0D0C25
header.bold=true

tab.fg=#312e55
tab.bg=${status.bg}
tab.selected.fg=#070614
tab.selected.bg=#3F3BF5

statusline_default.fg=#bec8e8
statusline_default.bg=#09081a
statusline_error.fg=#E50050
statusline_success.fg=#2A8A6B

*error.bold=true
*error.fg=#E50050
*warning.fg=#FB9B00
*success.fg=#2A8A6B

dirlist_*.bg=#0D0C25
dirlist_*.fg=#bec8e8
dirlist_*.selected.bg=#161440
dirlist_*.selected.fg=#bec8e8

msglist_*.bg=#0D0C25
msglist_*.fg=#bec8e8
msglist_*.selected.bg=#161440
#msglist_*.selected.fg=#bec8e8
msglist_unread.bold=true
msglist_unread.fg=#3F3BF5
msglist_marked.fg=#FB9B00
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#161440
msglist_pill.bg=#312e55
msglist_pill.reverse=false

part_*.fg=#bec8e8
part_*.bg=#070614
part_*.selected.fg=#bec8e8
part_*.selected.bg=#312e55

completion_default.bg=#070614
completion_default.fg=#bec8e8
completion_default.selected.bg=#312e55
completion_default.selected.fg=#bec8e8
completion_gutter.bg=#161440
completion_pill.bg=#312e55
completion_pill.reverse=false

spinner.bg=#0D0C25
spinner.fg=#bec8e8

selector_focused.bold=false
selector_focused.bg=#161440
selector_focused.fg=#bec8e8
selector_chooser.bold=false
selector_chooser.bg=#161440
selector_chooser.fg=#bec8e8
default.selected.bold=false
default.selected.fg=#bec8e8
default.selected.bg=#161440

[viewer]
url.underline=true
url.fg=#33D4B4
header.fg=#834CCF
signature.fg=#D91C87
diff_add.fg=#111f30
diff_del.fg=#2d0a2b
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#FFD888
quote_2.fg=#2A8A6B
quote_3.fg=#33D4B4
quote_3.dim=true
quote_4.fg=#3F3BF5
quote_4.dim=true
quote_x.fg=#5c6296
quote_x.dim=true

