# vim: ft=dosini
#
# aerc Arrowlake styleset
# set styleset-name=arrowlake-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#ad9b88
border.bg=#ebe0cf

title.fg=#DED0BF
title.bg=#4A74A8
title.bold=true

header.fg=#BC495D
#header.bg=#ebe0cf
header.bold=true

tab.fg=#ad9b88
tab.bg=${status.bg}
tab.selected.fg=#DED0BF
tab.selected.bg=#4A74A8

statusline_default.fg=#54473f
statusline_default.bg=#e3d7c7
statusline_error.fg=#BC495D
statusline_success.fg=#4E7469

*error.bold=true
*error.fg=#BC495D
*warning.fg=#AE984C
*success.fg=#4E7469

dirlist_*.bg=#ebe0cf
dirlist_*.fg=#54473f
dirlist_*.selected.bg=#d4c6b3
dirlist_*.selected.fg=#54473f

msglist_*.bg=#ebe0cf
msglist_*.fg=#54473f
msglist_*.selected.bg=#d4c6b3
#msglist_*.selected.fg=#54473f
msglist_unread.bold=true
msglist_unread.fg=#4A74A8
msglist_marked.fg=#CF9978
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#d4c6b3
msglist_pill.bg=#ad9b88
msglist_pill.reverse=false

part_*.fg=#54473f
part_*.bg=#DED0BF
part_*.selected.fg=#54473f
part_*.selected.bg=#ad9b88

completion_default.bg=#DED0BF
completion_default.fg=#54473f
completion_default.selected.bg=#ad9b88
completion_default.selected.fg=#54473f
completion_gutter.bg=#d4c6b3
completion_pill.bg=#ad9b88
completion_pill.reverse=false

spinner.bg=#ebe0cf
spinner.fg=#54473f

selector_focused.bold=false
selector_focused.bg=#d4c6b3
selector_focused.fg=#54473f
selector_chooser.bold=false
selector_chooser.bg=#d4c6b3
selector_chooser.fg=#54473f
default.selected.bold=false
default.selected.fg=#54473f
default.selected.bg=#d4c6b3

[viewer]
url.underline=true
url.fg=#CF9978
header.fg=#6660AF
signature.fg=#C16C90
diff_add.fg=#d3d0c0
diff_del.fg=#e4c9be
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#AE984C
quote_2.fg=#4E7469
quote_3.fg=#56AEA9
quote_3.dim=true
quote_4.fg=#4A74A8
quote_4.dim=true
quote_x.fg=#87786c
quote_x.dim=true

