# Arrowlake

# Syntax Highlighting Colors
fish_color_normal 54473f
fish_color_command 56AEA9
fish_color_keyword C16C90
fish_color_quote AE984C
fish_color_redirection 54473f
fish_color_end CF9978
fish_color_option C16C90
fish_color_error BC495D
fish_color_param 6660AF
fish_color_comment ${foregrounds.comment}
fish_color_selection --background=${backgrounds.visual}
fish_color_search_match --background=${backgrounds.visual}
fish_color_operator 4E7469
fish_color_escape C16C90
fish_color_autosuggestion ${foregrounds.comment}

# Completion Pager Colors
fish_pager_color_progress ${foregrounds.comment}
fish_pager_color_prefix 56AEA9
fish_pager_color_completion 54473f
fish_pager_color_description ${foregrounds.comment}
fish_pager_color_selected_background --background=${backgrounds.visual}
