[[themes]]
name = "Arrowlake Light"
[themes.palette]
background = "#e3d7c7"
foreground = "#6c5e55"
black = "#ad9b88"
red = "#BC495D"
green = "#4E7469"
yellow = "#AD8A5A"
blue = "#4A74A8"
magenta = "#C16C90"
cyan = "#56AEA9"
white = "#87786c"
bright_black = "#ebe0cf"
bright_red = "#BC495D"
bright_green = "#448474"
bright_yellow = "#C88478"
bright_blue = "#3782cb"
bright_magenta = "#db719f"
bright_cyan = "#6a8b89"
bright_white = "#54473f"
