[[themes]]
name = "Arrowlake"
[themes.palette]
background = "#09081a"
foreground = "#7e85b8"
black = "#070614"
red = "#E50050"
green = "#2A8A6B"
yellow = "#FFD888"
blue = "#3F3BF5"
magenta = "#D91C87"
cyan = "#33D4B4"
white = "#5c6296"
bright_black = "#0D0C25"
bright_red = "#E50050"
bright_green = "#009a74"
bright_yellow = "#FB9B00"
bright_blue = "#4f4cff"
bright_magenta = "#f50097"
bright_cyan = "#9AC1E5"
bright_white = "#bec8e8"
