attribute = { fg = "#33d4b4", modifiers = ["bold"] }
comment = { fg = "#5c6296", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#ffd888" }
constant = { fg = "#ffd888" }
"constant.builtin" = { fg = "#4948b4" }
"constant.builtin.boolean" = { fg = "#ffd888" }
"constant.character" = { fg = "#2a8a6b" }
"constant.character.escape" = { fg = "#d91c87" }
"constant.numeric" = { fg = "#ffd888" }
"constant.numeric.float" = { fg = "#ffd888" }
"constant.numeric.integer" = { fg = "#ffd888" }
constructor = { fg = "#5352cd" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#42393b", fg = "#ffd888" }
"diff.delta.moved" = { fg = "#3f3bf5" }
"diff.minus" = { bg = "#2d0a2b", fg = "#e50050" }
"diff.plus" = { bg = "#111f30", fg = "#2a8a6b" }
error = { fg = "#e50050" }
function = { fg = "#3f3bf5", modifiers = ["bold"] }
"function.builtin" = { fg = "#3834d6", modifiers = ["bold"] }
"function.macro" = { fg = "#33d4b4", modifiers = ["bold"] }
"function.method" = { fg = "#3f3bf5", modifiers = ["bold"] }
"function.special" = { fg = "#33d4b4", modifiers = ["bold"] }
hint = { fg = "#33d4b4" }
info = { fg = "#5352cd" }
keyword = { fg = "#d91c87", modifiers = ["italic"] }
"keyword.control" = { fg = "#d91c87" }
"keyword.control.conditional" = { fg = "#d91c87" }
"keyword.control.exception" = { fg = "#d91c87" }
"keyword.control.repeat" = { fg = "#d91c87" }
"keyword.control.return" = { fg = "#d91c87", modifiers = ["italic"] }
"keyword.directive" = { fg = "#33d4b4", modifiers = ["bold"] }
"keyword.function" = { fg = "#3f3bf5", modifiers = ["bold"] }
"keyword.operator" = { fg = "#d91c87" }
label = { fg = "#5352cd" }
"markup.bold" = { fg = "#bec8e8", modifiers = ["bold"] }
"markup.heading" = { fg = "#3f3bf5", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#070614", fg = "#bec8e8" }
"markup.heading.hover" = { bg = "#161440" }
"markup.italic" = { fg = "#bec8e8", modifiers = ["italic"] }
"markup.link" = { fg = "#33d4b4" }
"markup.link.label" = { fg = "#4948b4" }
"markup.link.text" = { fg = "#33d4b4" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#fb9b00" }
"markup.normal.completion" = { fg = "#5c6296" }
"markup.normal.hover" = { fg = "#7e85b8" }
"markup.raw" = { fg = "#2a8a6b" }
"markup.raw.inline" = { bg = "#09081a", fg = "#ffd888" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#33d4b4", modifiers = ["bold"] }
operator = { fg = "#9ac1e5" }
special = { fg = "#4948b4" }
string = { fg = "#2a8a6b" }
"string.regexp" = { fg = "#9ac1e5" }
"string.special" = { fg = "#4948b4" }
tag = { fg = "#d91c87" }
type = { fg = "#5352cd" }
"type.builtin" = { fg = "#4948b4" }
"type.enum" = { fg = "#5352cd" }
"type.enum.variant" = { fg = "#ffd888" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#bec8e8", fg = "#0d0c25" }
"ui.cursor.match" = { fg = "#fb9b00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#312e55" }
"ui.linenr.select" = { fg = "#fb9b00", modifiers = ["bold"] }
"ui.menu" = { bg = "#070614", fg = "#bec8e8" }
"ui.menu.scroll" = { bg = 1052703, fg = 3223125 }
"ui.menu.selected" = { bg = "#161440" }
"ui.popup" = { bg = "#070614", fg = "#3f3bf5" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#09081a", fg = "#5c6296" }
"ui.statusline.inactive" = { bg = "#09081a", fg = "#312e55" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#0d0c25", fg = "#bec8e8" }
"ui.text.focus" = { bg = "#161440" }
"ui.text.inactive" = { fg = "#5c6296", modifiers = ["italic"] }
"ui.text.info" = { bg = "#070614", fg = "#bec8e8" }
"ui.virtual.inlay-hint" = { bg = "#112033", fg = "#33d4b4" }
"ui.window" = { fg = "#09081a", modifiers = ["bold"] }
variable = { fg = "#bec8e8" }
"variable.builtin" = { fg = "#d91c87" }
"variable.other.member" = { fg = "#7e85b8" }
"variable.parameter" = { fg = "#ffd888" }
warning = { fg = "#fb9b00" }

[palette]
"backgrounds.code" = "#09081a"
"backgrounds.color_column" = "#070614"
"backgrounds.dark" = "#09081a"
"backgrounds.darker" = "#070614"
"backgrounds.float" = "#070614"
"backgrounds.fold" = "#070614"
"backgrounds.highlight" = "#161440"
"backgrounds.hover" = "#161440"
"backgrounds.input" = "#070614"
"backgrounds.normal" = "#0D0C25"
"backgrounds.notification" = "#09081a"
"backgrounds.search" = "#161440"
"backgrounds.search_current" = "#691351"
"backgrounds.sidebar" = "#070614"
"backgrounds.statusline" = "#09081a"
"backgrounds.tabline" = "#09081a"
"backgrounds.tabline_fill" = "#09081a"
"backgrounds.visual" = "#161440"
"backgrounds.which_key" = "#09081a"
"backgrounds.winbar" = "#09081a"
bg = "#0D0C25"
bg_dark = "#09081a"
bg_darker = "#070614"
blue = "#3F3BF5"
"border.active" = "#FB9B00"
"border.active_title" = "#FB9B00"
"border.color" = "#3F3BF5"
"border.split" = "#09081a"
"border.subtle" = "#5c6296"
"border.title" = "#3F3BF5"
cyan = "#33D4B4"
"diagnostics.error" = "#E50050"
"diagnostics.hint" = "#33D4B4"
"diagnostics.info" = "#5352CD"
"diagnostics.success" = "#2A8A6B"
"diagnostics.todo" = "#5352CD"
"diagnostics.trace" = "#834CCF"
"diagnostics.warning" = "#FB9B00"
"diff.add" = "#111f30"
"diff.change" = "#42393b"
"diff.delete" = "#2d0a2b"
"diff.text" = "#152d37"
fg = "#bec8e8"
fg_dark = "#7e85b8"
fg_darker = "#5c6296"
fg_gutter = "#312e55"
focus = "#FB9B00"
"foregrounds.comment" = "#5c6296"
"foregrounds.dark" = "#7e85b8"
"foregrounds.darker" = "#5c6296"
"foregrounds.indent" = "#312e55"
"foregrounds.member" = "#7e85b8"
"foregrounds.muted" = "#312e55"
"foregrounds.normal" = "#bec8e8"
"foregrounds.punctuation" = "#7e85b8"
"foregrounds.sidebar" = "#5c6296"
"foregrounds.statusline" = "#5c6296"
"foregrounds.tabline" = "#3F3BF5"
"foregrounds.winbar" = "#5c6296"
"git.add" = "#2A8A6B"
"git.change" = "#FFD888"
"git.delete" = "#E50050"
"git.ignore" = "#5c6296"
green = "#2A8A6B"
magenta = "#D91C87"
orange = "#FB9B00"
primary = "#3F3BF5"
purple = "#834CCF"
rainbow = "#3F3BF5"
"rainbow.2" = "#FFD888"
"rainbow.3" = "#D91C87"
"rainbow.4" = "#2A8A6B"
"rainbow.5" = "#33D4B4"
"rainbow.6" = "#834CCF"
"rainbow.7" = "#E50050"
"rainbow.8" = "#FB9B00"
red = "#E50050"
secondary = "#5352CD"
selection = "#161440"
special = "#9AC1E5"
"status.command" = "#FB9B00"
"status.inactive" = "#070614"
"status.insert" = "#2A8A6B"
"status.normal" = "#3F3BF5"
"status.replace" = "#E50050"
"status.terminal" = "#33D4B4"
"status.visual" = "#D91C87"
"syntax.constant" = "#FFD888"
"syntax.constructor" = "#D91C87"
"syntax.functions" = "#3F3BF5"
"syntax.functions_builtin" = "#3834d6"
"syntax.keyword" = "#D91C87"
"syntax.link" = "#33D4B4"
"syntax.macro" = "#33D4B4"
"syntax.markup" = "#FB9B00"
"syntax.md_inline" = "#FFD888"
"syntax.operator" = "#9AC1E5"
"syntax.parameter" = "#FFD888"
"syntax.string" = "#2A8A6B"
"syntax.string_doc" = "#FFD888"
"syntax.string_escape" = "#D91C87"
"syntax.type" = "#5352CD"
"syntax.type_builtin" = "#4948b4"
"syntax.variable" = "#bec8e8"
"terminal.black" = "#070614"
"terminal.black_bright" = "#312e55"
"terminal.blue" = "#3F3BF5"
"terminal.blue_bright" = "#4f4cff"
"terminal.cyan" = "#33D4B4"
"terminal.cyan_bright" = "#00e5c0"
"terminal.green" = "#2A8A6B"
"terminal.green_bright" = "#009a74"
"terminal.magenta" = "#D91C87"
"terminal.magenta_bright" = "#f50097"
"terminal.red" = "#E50050"
"terminal.red_bright" = "#fd0059"
"terminal.white" = "#5c6296"
"terminal.white_bright" = "#bec8e8"
"terminal.yellow" = "#FFD888"
"terminal.yellow_bright" = "#ffe8c2"
"ui.ai" = "#33D4B4"
"ui.attention" = "#D91C87"
"ui.cursor_bg" = "#bec8e8"
"ui.cursor_fg" = "#0D0C25"
"ui.footer" = "#5352CD"
"ui.header" = "#3F3BF5"
"ui.icon" = "#5352CD"
"ui.label" = "#5352CD"
"ui.path" = "#3F3BF5"
"ui.prompt" = "#3F3BF5"
yellow = "#FFD888"