---@class arrowlake.PaletteGit
---@field add string
---@field change string
---@field delete string
---@field ignore string

---@class arrowlake.PaletteDiff
---@field add string
---@field change string
---@field delete string
---@field text string

---@class arrowlake.PaletteTerminal
---@field black string
---@field black_bright string
---@field red string
---@field red_bright string
---@field green string
---@field green_bright string
---@field yellow string
---@field yellow_bright string
---@field blue string
---@field blue_bright string
---@field magenta string
---@field magenta_bright string
---@field cyan string
---@field cyan_bright string
---@field white string
---@field white_bright string

---@class arrowlake.PaletteStatus
---@field normal string
---@field insert string
---@field command string
---@field visual string
---@field replace string
---@field terminal string
---@field inactive string

---@class arrowlake.PaletteBackgrounds
---@field normal string
---@field dark string
---@field darker string
---@field code string
---@field input string
---@field notification string
---@field sidebar string
---@field statusline string
---@field tabline string
---@field tabline_fill string
---@field winbar string
---@field float string
---@field which_key string
---@field highlight string
---@field visual string
---@field hover string
---@field search string
---@field search_current string
---@field color_column string
---@field fold string

---@class arrowlake.PaletteForegrounds
---@field normal string
---@field dark string
---@field darker string
---@field comment string
---@field muted string
---@field sidebar string
---@field statusline string
---@field tabline string
---@field winbar string
---@field member string
---@field punctuation string
---@field indent string

---@class arrowlake.PaletteBorder
---@field active string
---@field active_title string
---@field split string
---@field title string
---@field color string
---@field subtle string

---@class arrowlake.PaletteUI
---@field cursor_bg string
---@field cursor_fg string
---@field attention string
---@field ai string
---@field prompt string
---@field header string
---@field path string
---@field footer string
---@field icon string
---@field label string

---@class arrowlake.PaletteSyntax
---@field title string
---@field keyword string
---@field macro string
---@field string string
---@field string_doc string
---@field string_escape string
---@field md_inline string
---@field parameter string
---@field variable string
---@field constant string
---@field type string
---@field type_builtin string
---@field functions string
---@field functions_builtin string
---@field constructor string
---@field operator string
---@field markup string
---@field link string

---@class arrowlake.PaletteDiagnostics
---@field error string
---@field warning string
---@field info string
---@field hint string
---@field success string
---@field todo string
---@field trace string

---@class arrowlake.Palette
---@field bg string
---@field bg_dark string
---@field bg_darker string
---@field fg string
---@field fg_dark string
---@field fg_darker string
---@field fg_gutter string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field blue string
---@field purple string
---@field magenta string
---@field cyan string
---@field primary string
---@field secondary string
---@field selection string
---@field focus string
---@field special string
---@field rainbow string[]
---@field git arrowlake.PaletteGit
---@field diff arrowlake.PaletteDiff
---@field terminal arrowlake.PaletteTerminal
---@field status arrowlake.PaletteStatus
---@field backgrounds arrowlake.PaletteBackgrounds
---@field foregrounds arrowlake.PaletteForegrounds
---@field border arrowlake.PaletteBorder
---@field ui arrowlake.PaletteUI
---@field syntax arrowlake.PaletteSyntax
---@field diagnostics arrowlake.PaletteDiagnostics
---@field map? fun(c: arrowlake.Palette)
---@field none string

---Bare class so ColorScheme resolves everywhere without arrowlake. prefix
---(same pattern aether.nvim uses)
---@class ColorScheme: arrowlake.Palette
---@field none "NONE"

---@alias arrowlake.ColorScheme ColorScheme
---@alias Palette arrowlake.Palette

---@class arrowlake.Highlight: vim.api.keyset.highlight
---@field style? vim.api.keyset.highlight

---@alias arrowlake.Highlights table<string, arrowlake.Highlight|string>

---@alias arrowlake.HighlightsFn fun(colors: arrowlake.ColorScheme, opts: arrowlake.Config): arrowlake.Highlights

---@class arrowlake.Cache
---@field groups arrowlake.Highlights
---@field inputs table
