# vim:ft=kitty

## name: Arrowlake Light
## license: MIT
## author: Jadon Brutcher
## upstream: https://github.com/jadonwb/arrowlake.nvim/raw/main/extras/kitty/arrowlake_light.conf


background #ebe0cf
foreground #54473f
selection_background #d4c6b3
selection_foreground #54473f
url_color #C88478
cursor #54473f
cursor_text_color #ebe0cf

# Tabs
active_tab_background #6660AF
active_tab_foreground #e3d7c7
inactive_tab_background #d4c6b3
inactive_tab_foreground #87786c
#tab_bar_background #DED0BF

# Windows
active_border_color #6660AF
inactive_border_color #e3d7c7

# normal
color0 #DED0BF
color1 #BC495D
color2 #4E7469
color3 #AD8A5A
color4 #4A74A8
color5 #C16C90
color6 #56AEA9
color7 #87786c

# bright
color8  #ad9b88
color9  #e43b5f
color10 #448474
color11 #c59546
color12 #3782cb
color13 #db719f
color14 #2dc0ba
color15 #54473f

# extended colors
color16 #C88478
color17 #BC495D
