# -----------------------------------------------------------------------------
# Theme: Arrowlake
# Upstream: https://github.com/jadonwb/arrowlake.nvim/raw/main/extras/termux/arrowlake_dark.properties
# -----------------------------------------------------------------------------

background: #0D0C25
foreground: #bec8e8

# Normal colors
color0:  #070614
color1:  #E50050
color2:  #2A8A6B
color3:  #FFD888
color4:  #3F3BF5
color5:  #D91C87
color6:  #33D4B4
color7:  #5c6296

# Bright colors
color8:  #312e55
color9:  #fd0059
color10: #009a74
color11: #ffe8c2
color12: #4f4cff
color13: #f50097
color14: #00e5c0
color15: #bec8e8

# Extended colors
color16: #FB9B00
color17: #E50050
